Repository racionais-app/mobile, pull requests merged in 2021-04, with the labels that each got.

#3 [NEW] YouTube Player
  app/Root.js
  app/screens/Explanation/index.js
  ios/Podfile.lock
  package.json
Labels: enhancement

#2 [NEW] Question Screen using Server-Driven-UI
  app/Root.js
  app/containers/DailyBalance.js
  app/containers/HeaderButton.js
  app/containers/HeartBalance.js
  app/containers/StarBalance.js
  app/core/store.js
  app/resources/module.png
  app/resources/onboarding.png
  app/screens/Explanation/index.js
  app/screens/Home/Header.js
  app/screens/Home/index.js
  app/screens/Login/index.js
  app/screens/Module/index.js
  app/screens/Question/Components/Element.js
  app/screens/Question/Components/Footer.js
  app/screens/Question/Components/Image.js
  app/screens/Question/Components/Input.js
  app/screens/Question/Components/Markdown.js
  app/screens/Question/Components/Select.js
  app/screens/Question/Components/Separator.js
  app/screens/Question/Components/Text.js
  app/screens/Question/index.js
  app/screens/Settings/index.js
  ios/Podfile
  ios/Podfile.lock
  ios/racionais.xcodeproj/project.pbxproj
  ios/racionais/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/racionais/Info.plist
  package.json
  patches/react-native-markdown-display+7.0.0-alpha.2.patch
  yarn.lock
Labels: enhancement

#5 [NEW] Progress
  app/core/Module.js
  app/core/data.js
  app/screens/Home/index.js
  app/screens/Module/index.js
  app/screens/Question/index.js
  package.json
  yarn.lock
Labels: enhancement

#6 [BUGFIX] Tutorial Ballons
  app/screens/Module/index.js
  app/screens/Question/Components/Input.js
  app/screens/Question/index.js
Labels: bug

#7 [FEATURE] Fraction
  android/app/build.gradle
  android/app/src/main/java/com/racionais/MainApplication.java
  android/gradle.properties
  app/screens/Question/Components/Element.js
  app/screens/Question/Components/Footer.js
  app/screens/Question/Components/Fraction.js
  app/screens/Question/Components/Input.js
  app/screens/Question/index.js
Labels: enhancement

#8 [FEATURE] Analytics
  .gitignore
  android/app/build.gradle
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  app/Root.js
  app/containers/StarBalance.js
  app/resources/hearth.png
  app/screens/Home/index.js
  app/screens/Login/index.js
  app/screens/Module/index.js
  app/screens/Onboarding/index.js
  app/screens/Question/Components/Footer.js
  app/screens/Question/index.js
  ios/Podfile.lock
  package.json
  patches/react-native-onboarding-swiper+1.1.4.patch
  yarn.lock
Labels: enhancement

#9 [FIX] Android Keyboard
  app/screens/Question/index.js
Labels: bug

#10 [DOCS] README
  README.md
Labels: documentation

#11 [DOCS] Update documentation images
  README.md
Labels: documentation

#12 [FIX] Minor changes
  app/core/Module.js
  app/screens/Home/index.js
  app/screens/Module/index.js
  app/screens/Question/Components/Fraction.js
  app/screens/Question/index.js
  ios/Podfile.lock
  ios/racionais.xcodeproj/project.pbxproj
Labels: bug
